---
- name: install kibana
  hosts: kibana
  become: yes
  become_user: root
  tasks:
    - name: Download rpm file from server
      ansible.builtin.get_url:
        url: https://artifacts.elastic.co/downloads/kibana/kibana-8.4.2-x86_64.rpm
        dest: /tmp/kibana-8.4.2-x86_64.rpm
        mode: 0644
        owner: huray
        validate_certs: no
    - name: Install package
      yum:
        name: /tmp/kibana-8.4.2-x86_64.rpm
        state: present
    - name: Check working directory exists
      ansible.builtin.stat:
        path: /elk-stack
      register: workdir
    - name: If directory already existed
      debug:
        msg: /elk-stack is already existed
      when: workdir.stat.exists
    - name: Create workdir if not exists
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
        mode: 0755
        group: huray
        owner: huray
      with_items:
        - "/elk-stack"
        - "/elk-stack/bin"
        - "/elk-stack/etc"
        - "/elk-stack/var"
      when: workdir.stat.exists == false
    - name: Copy kibana main config files
      ansible.builtin.copy:
        src: "../kibana/config/dev/kibana.yml"
        dest: "/etc/kibana/kibana.yml"
        mode: 0644
        owner: root
        group: kibana
    - name: Reload daemon
      ansible.builtin.shell: systemctl daemon-reload
    - name: Restart Kibana
      ansible.builtin.shell: systemctl restart kibana

